@tidl 1.0.0;

interface Price exposes PriceService {

	@description
"# Overview
API to interact with Tesco's base product management processes & product details.

## Purpose
Price Api can be used for price information.
## Examples
```e.g. in http
http://api.example.com/v1/price/...
``` ";

    @owner "Product and Price Services Team", "Product and Price Services team email", "1.0.0";
	@author "Maria Gomez / Minno Dang", "Maria.Gomez@uk.tesco.com / Minno.Dang@uk.tesco.com", "1.0.0";
	@reviewer "", "","", "";

	@organisation "Tesco";
	@organisationDomainName "example.com";
	@namespacePrefix "example.com.services";
	@version 1.0.0, "draft","2013/6/25","first draft of version 1.0";

    list<Price> get(mandatory string itemNumber, string store, string callback) throws PriceUnavailableException {
    	@description
        "
        #Overview
          End point to retrieve information about price for a product by product item number
        ##Example
          $ curl -I http://<hostname>/price/059310015
            HTTP/1.1 200 OK
            Content-Type: application/json
            
          $ curl http://<hostname>/price/059310015
            [{\"itemNumber\":\"059310015\",\"price\":\"5\",\"promoPrice\":\"5\",\"currency\":\"GBP\"}]

       	  Get price for a product with store id
          $ curl http://<hostname>/price/059310015?store=2031
       "  ;

        @parameter itemNumber, "the identifier for the product to fetch price of";
        @parameter store, "Store from where to fetch the price for the product";
        @parameter callback, "optional callback to be executed";
        @return "Price information for a product";
        @since 1.0.0;
    }

    type Price(string itemNumber, string price, string promoPrice, string currency) {
        @description "";
        @parameter itemNumber, "";
        @parameter price, "";
        @parameter promoPrice, "";
        @parameter currency, "";
    }

	exception PriceUnavailableException(
		string message,
		HttpStatusCode statusCode)
	{
		@description "Exception indicating that no price for the item was found.";
		@parameter message, "No price for the item was found";
		@parameter statusCode, "Http status code.";
	}

}