@tidl 1.0.0;

interface Promotion exposes PromotionService {

@description
"# Overview
API for retrieving promotional information.

## Purpose
Promotion Api can be used for obtaining promotion information.
";

  @owner "Product and Price Services Team", "Product and Price Services team email", "1.0.0";
	@author "Maria Gomez / Minno Dang", "Maria.Gomez@uk.tesco.com / Minno.Dang@uk.tesco.com", "1.0.0";
	@reviewer "", "","", "";

	@organisation "Tesco";
	@organisationDomainName "example.com";
	@namespacePrefix "example.com.services";
	@version 1.0.0, "draft","2013/6/25","first draft of version 1.0";

   list<Promotion> getFind(mandatory PromotionNumberZoneTPNBs promotionNumberZoneTPNBsFromBody) {
    	@description
        '''
        #Overview
          End point to retrieve batch promotion information for a list of promotion-zone-tpnb combinations.
          By passing a store number and tbnb results are filter so you only get back promotions in the promotion zone the store is in
        ##Example Request - Response

        Request:
          POST http://<hostname>[:<port>]/promotion/find
          content-type:application/json
          {
             "promotions":[
                {
                   "offerId":"A29721688",
                   "itemNumber":"070918248",
                   "zoneId":"6"
                }
             ]
          }

        Response:
          [
            {
              "shelfTalkerImage":null,
              "offerId":"A29721688",
              "itemNumber":"070918248",
              "zoneId":"6",
              "CFDescription1":"SPECIAL PURCHASE 50p",
              "CFDescription2":"3 LIONS|WATERBOTTLE",
              "offerName":"3 LIONS KICK & TRICK BALL 1.00 SPECIAL PURCHASE",
              "startDate":"31-Apr-12",
              "endDate":"04-May-13",
              "cfdescription2":"3 LIONS|WATERBOTTLE",
              "cfdescription1":"SPECIAL PURCHASE 50p"
            }
          ]

         Command-line example:
          curl -H "content-type:application/json" -d "{\"promotions\":[{\"offerId\":\"A29721688\",\"itemNumber\":\"070918248\",\"zoneId\":\"6\"}]}" http://<host>[:<port>]/promotion/find
        ''';
        @return "List of Promotion information";
        @since 1.0.0;
    }

    type Promotion(string itemNumber,string offerId, string offerName, string zoneId, string cfdescription1, string cfdescription2, string shelfTalkerImage, string startDate, string endDate) {
      @description "Promotion";
      @parameter itemNumber, "TPNB (Base, if a variant)";
      @parameter offerId, "Unique Identifier for Promotion";
      @parameter offerName, "Name of Promotion";
      @parameter zoneId, "Zone the promotion applies to";
      @parameter cfdescription1, "";
      @parameter cfdescription2, "";
      @parameter shelfTalkerImage, "Promotional sticker image used in stores";
      @parameter startDate, "Promotion Start Date";
      @parameter endDate, "Promotion End Date";
    }

	exception PromotionUnavailableException( string message, HttpStatusCode statusCode)
	{
		@description "Exception indicating that no promotions were found.";
		@parameter message, "Promotions not found";
		@parameter statusCode, "404";
	}
}